"""
Signal Engine
- Combines technical analysis + news sentiment into actionable signals
- Applies thresholds and cooldowns
"""
import logging
import hashlib
from datetime import datetime, timedelta
from typing import Dict, List, Optional, Any, Tuple
from dataclasses import dataclass, field

from src.utils.logger import get_logger
from src.analysis.technical import IndicatorSnapshot

logger = get_logger(__name__)


@dataclass
class Signal:
    """A trading signal generated by the engine"""
    symbol: str
    action: str          # STRONG_BUY / BUY / WATCH / SELL / STRONG_SELL
    direction: str       # LONG or SHORT
    strength: float      # -100..+100 composite score

    price: float
    change_pct: float
    timeframe: str
    technical_score: float

    news_score: float = 0.0
    news_headline: str = ""
    news_keywords: List[str] = field(default_factory=list)

    stop_loss: Optional[float] = None
    take_profit_1: Optional[float] = None
    take_profit_2: Optional[float] = None
    risk_reward_ratio: float = 0.0

    indicators: Optional[IndicatorSnapshot] = None

    timestamp: datetime = field(default_factory=datetime.utcnow)
    signal_id: str = ""
    reasons: List[str] = field(default_factory=list)

    def __post_init__(self):
        raw = f"{self.symbol}_{self.action}_{self.timestamp.strftime('%Y%m%d%H%M')}"
        self.signal_id = hashlib.md5(raw.encode()).hexdigest()[:12]


class SignalEngine:
    """Combines TA + news into signals"""

    def __init__(self, config: Dict[str, Any]):
        self.config = config
        self.thresholds = config.get("thresholds", {})
        self.risk_config = config.get("risk", {})

        self.strong_buy = self.thresholds.get("strong_buy", 75)
        self.buy = self.thresholds.get("buy", 60)
        self.watch = self.thresholds.get("watch", 45)
        self.strong_sell = self.thresholds.get("strong_sell", -75)
        self.sell = self.thresholds.get("sell", -60)

        self.atr_sl_mult = self.risk_config.get("atr_sl_multiplier", 1.5)
        self.atr_tp1_mult = self.risk_config.get("atr_tp1_multiplier", 2.0)
        self.atr_tp2_mult = self.risk_config.get("atr_tp2_multiplier", 3.0)
        self.max_signals_per_hour = self.risk_config.get("max_signals_per_hour", 10)
        self.cooldown_minutes = self.risk_config.get("signal_cooldown_minutes", 15)
        self.min_rr = self.risk_config.get("min_risk_reward_ratio", 1.5)

        self.news_config = config.get("news", {})
        self.keyword_boost_max = self.news_config.get("keyword_boost_max", 30)

        self._recent_signals: Dict[str, List[datetime]] = {}

    def _apply_news_boost(self, technical_score: float, news_agg: Dict[str, Any]) -> Tuple[float, float, str, List[str]]:
        """Boost/penalize technical score with news sentiment"""
        news_score = 0.0
        headline = ""
        keywords = []

        if news_agg:
            news_score = float(news_agg.get("score", 0))
            headline = news_agg.get("latest_article", "") or ""
            top_kw = news_agg.get("top_keywords", []) or []
            keywords = [k.get("keyword", "") for k in top_kw]

        scaled_news = news_score * 0.6
        if abs(scaled_news) < 3:
            scaled_news = 0.0

        combined = technical_score + scaled_news
        return combined, news_score, headline, keywords

    def _calculate_risk_levels(self, snap: IndicatorSnapshot, direction: str) -> Tuple[Optional[float], Optional[float], Optional[float], float]:
        """Calculate SL/TP based on ATR"""
        if not snap or snap.atr_14 <= 0:
            return None, None, None, 0.0

        atr = snap.atr_14
        price = snap.price

        if direction == "LONG":
            sl = price - (atr * self.atr_sl_mult)
            tp1 = price + (atr * self.atr_tp1_mult)
            tp2 = price + (atr * self.atr_tp2_mult)
        else:
            sl = price + (atr * self.atr_sl_mult)
            tp1 = price - (atr * self.atr_tp1_mult)
            tp2 = price - (atr * self.atr_tp2_mult)

        risk = abs(price - sl)
        reward = abs(tp1 - price)
        rr = reward / risk if risk > 0 else 0.0

        return sl, tp1, tp2, rr

    def _build_reasons(self, snap: IndicatorSnapshot, news_agg: Dict[str, Any]) -> List[str]:
        """Build human-readable reason list"""
        reasons = []

        if not snap:
            return reasons

        if snap.is_breakout_up:
            reasons.append("📈 Donchian/BB üst band kırılımı")
        if snap.is_breakout_down:
            reasons.append("📉 Donchian/BB alt band kırılımı")
        if snap.is_volume_spike:
            reasons.append(f"🔊 Hacim patlaması ({snap.volume_ratio:.1f}x)")
        if snap.is_golden_cross:
            reasons.append("✨ EMA 9/21 Golden Cross")
        if snap.is_death_cross:
            reasons.append("💀 EMA 9/21 Death Cross")
        if snap.is_vwap_reclaim:
            reasons.append("🎯 VWAP geri kazanımı")
        if snap.rsi_14 > 65:
            reasons.append(f"⚡ RSI güçlü ({snap.rsi_14:.0f})")
        if snap.rsi_14 < 35:
            reasons.append(f"🔄 RSI zayıf ({snap.rsi_14:.0f})")
        if abs(snap.change_pct) >= 1.0:
            reasons.append(f"🚀 {snap.change_pct:+.2f}% hareket")

        if news_agg:
            ns = float(news_agg.get("score", 0))
            if ns >= 5:
                reasons.append(f"📰 Pozitif haber akışı ({ns:+.1f})")
            elif ns <= -5:
                reasons.append(f"📰 Negatif haber akışı ({ns:+.1f})")

            headline = news_agg.get("latest_article", "")
            if headline:
                reasons.append(f"📋 {headline[:80]}{'...' if len(headline) > 80 else ''}")

        return reasons

    def is_in_cooldown(self, symbol: str) -> bool:
        """Check if symbol is in cooldown"""
        now = datetime.utcnow()
        signals = self._recent_signals.get(symbol, [])
        self._recent_signals[symbol] = [s for s in signals if (now - s).total_seconds() / 60 < self.cooldown_minutes]
        return len(self._recent_signals[symbol]) > 0

    def _record_signal(self, symbol: str):
        """Record a signal for cooldown tracking"""
        now = datetime.utcnow()
        if symbol not in self._recent_signals:
            self._recent_signals[symbol] = []
        self._recent_signals[symbol].append(now)

        cutoff = now - timedelta(hours=1)
        self._recent_signals[symbol] = [s for s in self._recent_signals[symbol] if s > cutoff]
        if len(self._recent_signals[symbol]) > self.max_signals_per_hour:
            self._recent_signals[symbol] = self._recent_signals[symbol][-self.max_signals_per_hour:]

    def evaluate(self, snap: Optional[IndicatorSnapshot], news_agg: Optional[Dict[str, Any]] = None) -> Optional[Signal]:
        """Evaluate a single symbol's snapshot against thresholds"""
        if not snap:
            return None

        if self.is_in_cooldown(snap.symbol):
            return None

        tech_score = snap.composite_score
        combined, news_score, headline, keywords = self._apply_news_boost(tech_score, news_agg or {})

        if combined >= self.strong_buy:
            action, direction = "STRONG_BUY", "LONG"
        elif combined >= self.buy:
            action, direction = "BUY", "LONG"
        elif combined >= self.watch:
            return None
        elif combined <= self.strong_sell:
            action, direction = "STRONG_SELL", "SHORT"
        elif combined <= self.sell:
            action, direction = "SELL", "SHORT"
        else:
            return None

        sl, tp1, tp2, rr = self._calculate_risk_levels(snap, direction)

        if rr < self.min_rr:
            logger.debug(f"Signal rejected: RR {rr:.2f} < {self.min_rr} for {snap.symbol}")
            return None

        reasons = self._build_reasons(snap, news_agg or {})

        signal = Signal(
            symbol=snap.symbol,
            action=action,
            direction=direction,
            strength=combined,
            price=snap.price,
            change_pct=snap.change_pct,
            timeframe=snap.timeframe,
            technical_score=tech_score,
            news_score=news_score,
            news_headline=headline,
            news_keywords=keywords,
            stop_loss=sl,
            take_profit_1=tp1,
            take_profit_2=tp2,
            risk_reward_ratio=rr,
            indicators=snap,
            reasons=reasons,
        )

        self._record_signal(snap.symbol)

        logger.info(f"🚨 Signal generated: {signal.action} {signal.symbol} @ {signal.price:.2f} "
                    f"(score={signal.strength:+.1f}, RR={signal.risk_reward_ratio:.2f})")

        return signal

    def evaluate_all(self, snapshots: Dict[str, Dict[str, IndicatorSnapshot]],
                     news_data: Optional[Dict[str, Dict[str, Any]]] = None) -> List[Signal]:
        """Evaluate all symbols and timeframes"""
        signals = []

        for symbol, tfs in snapshots.items():
            symbol_news = None
            if news_data:
                symbol_news = news_data.get(symbol)

            for tf, snap in tfs.items():
                try:
                    signal = self.evaluate(snap, symbol_news)
                    if signal:
                        signals.append(signal)
                except Exception as e:
                    logger.error(f"Evaluation error for {symbol} {tf}: {e}")

        signals.sort(key=lambda s: abs(s.strength), reverse=True)
        return signals

    def get_status(self) -> Dict[str, Any]:
        """Get engine status"""
        return {
            "recent_signals": {k: len(v) for k, v in self._recent_signals.items()},
            "cooldown_minutes": self.cooldown_minutes,
            "max_signals_per_hour": self.max_signals_per_hour,
            "thresholds": self.thresholds,
        }
